package com.hei.project2p1.controller.utils;

import java.util.ArrayList;
import java.util.List;

public class CountryCode {
    public static List<String> getCountryCodes() {
        List<String> countryCodes = new ArrayList<>();
        countryCodes.add("+93");
        countryCodes.add("+355");
        countryCodes.add("+213");
        countryCodes.add("+376");
        countryCodes.add("+244");
        countryCodes.add("+1 (268)");
        countryCodes.add("+54");
        countryCodes.add("+374");
        countryCodes.add("+61");
        countryCodes.add("+43");
        countryCodes.add("+994");
        countryCodes.add("+1 (242)");
        countryCodes.add("+973");
        countryCodes.add("+880");
        countryCodes.add("+1 (246)");
        countryCodes.add("+375");
        countryCodes.add("+32");
        countryCodes.add("+501");
        countryCodes.add("+229");
        countryCodes.add("+975");
        countryCodes.add("+591");
        countryCodes.add("+387");
        countryCodes.add("+267");
        countryCodes.add("+55");
        countryCodes.add("+673");
        countryCodes.add("+359");
        countryCodes.add("+226");
        countryCodes.add("+257");
        countryCodes.add("+238");
        countryCodes.add("+855");
        countryCodes.add("+237");
        countryCodes.add("+1");
        countryCodes.add("+236");
        countryCodes.add("+235");
        countryCodes.add("+56");
        countryCodes.add("+86");
        countryCodes.add("+57");
        countryCodes.add("+269");
        countryCodes.add("+243");
        countryCodes.add("+242");
        countryCodes.add("+506");
        countryCodes.add("+225");
        countryCodes.add("+385");
        countryCodes.add("+53");
        countryCodes.add("+357");
        countryCodes.add("+420");
        countryCodes.add("+45");
        countryCodes.add("+253");
        countryCodes.add("+1 (767)");
        countryCodes.add("+1 (809, 829, 849)");
        countryCodes.add("+593");
        countryCodes.add("+20");
        countryCodes.add("+503");
        countryCodes.add("+240");
        countryCodes.add("+291");
        countryCodes.add("+372");
        countryCodes.add("+268");
        countryCodes.add("+251");
        countryCodes.add("+679");
        countryCodes.add("+358");
        countryCodes.add("+33");
        countryCodes.add("+241");
        countryCodes.add("+220");
        countryCodes.add("+995");
        countryCodes.add("+49");
        countryCodes.add("+233");
        countryCodes.add("+30");
        countryCodes.add("+1 (473)");
        countryCodes.add("+502");
        countryCodes.add("+224");
        countryCodes.add("+245");
        countryCodes.add("+592");
        countryCodes.add("+509");
        countryCodes.add("+504");
        countryCodes.add("+36");
        countryCodes.add("+354");
        countryCodes.add("+91");
        countryCodes.add("+62");
        countryCodes.add("+98");
        countryCodes.add("+964");
        countryCodes.add("+353");
        countryCodes.add("+972");
        countryCodes.add("+39");
        countryCodes.add("+1 (876)");
        countryCodes.add("+81");
        countryCodes.add("+962");
        countryCodes.add("+7");
        countryCodes.add("+254");
        countryCodes.add("+686");
        countryCodes.add("+850");
        countryCodes.add("+82");
        countryCodes.add("+965");
        countryCodes.add("+996");
        countryCodes.add("+856");
        countryCodes.add("+371");
        countryCodes.add("+961");
        countryCodes.add("+266");
        countryCodes.add("+231");
        countryCodes.add("+218");
        countryCodes.add("+423");
        countryCodes.add("+370");
        countryCodes.add("+352");
        countryCodes.add("+261");
        countryCodes.add("+265");
        countryCodes.add("+60");
        countryCodes.add("+960");
        countryCodes.add("+223");
        countryCodes.add("+356");
        countryCodes.add("+692");
        countryCodes.add("+222");
        countryCodes.add("+230");
        countryCodes.add("+52");
        countryCodes.add("+691");
        countryCodes.add("+373");
        countryCodes.add("+377");
        countryCodes.add("+976");
        countryCodes.add("+382");
        countryCodes.add("+212");
        countryCodes.add("+258");
        countryCodes.add("+95");
        countryCodes.add("+264");
        countryCodes.add("+674");
        countryCodes.add("+977");
        countryCodes.add("+31");
        countryCodes.add("+64");
        countryCodes.add("+505");
        countryCodes.add("+227");
        countryCodes.add("+234");
        countryCodes.add("+389");
        countryCodes.add("+47");
        countryCodes.add("+968");
        countryCodes.add("+92");
        countryCodes.add("+680");
        countryCodes.add("+507");
        countryCodes.add("+675");
        countryCodes.add("+595");
        countryCodes.add("+51");
        countryCodes.add("+63");
        countryCodes.add("+48");
        countryCodes.add("+351");
        countryCodes.add("+974");
        countryCodes.add("+40");
        countryCodes.add("+7");
        countryCodes.add("+250");
        countryCodes.add("+1 (869)");
        countryCodes.add("+1 (758)");
        countryCodes.add("+1 (784)");
        countryCodes.add("+685");
        countryCodes.add("+378");
        countryCodes.add("+239");
        countryCodes.add("+966");
        countryCodes.add("+221");
        countryCodes.add("+381");
        countryCodes.add("+248");
        countryCodes.add("+232");
        countryCodes.add("+65");
        countryCodes.add("+421");
        countryCodes.add("+386");
        countryCodes.add("+677");
        countryCodes.add("+252");
        countryCodes.add("+27");
        countryCodes.add("+211");
        countryCodes.add("+34");
        countryCodes.add("+94");
        countryCodes.add("+249");
        countryCodes.add("+597");
        countryCodes.add("+46");
        countryCodes.add("+41");
        countryCodes.add("+963");
        countryCodes.add("+886");
        countryCodes.add("+992");
        countryCodes.add("+255");
        countryCodes.add("+66");
        countryCodes.add("+670");
        countryCodes.add("+228");
        countryCodes.add("+676");
        countryCodes.add("+1 (868)");
        countryCodes.add("+216");
        countryCodes.add("+90");
        countryCodes.add("+993");
        countryCodes.add("+688");
        countryCodes.add("+256");
        countryCodes.add("+380");
        countryCodes.add("+971");
        countryCodes.add("+44");
        countryCodes.add("+1");
        countryCodes.add("+598");
        countryCodes.add("+998");
        countryCodes.add("+678");
        countryCodes.add("+39");
        countryCodes.add("+58");
        countryCodes.add("+84");
        countryCodes.add("+967");
        countryCodes.add("+260");
        countryCodes.add("+263");

        return countryCodes;
    }

}
